import React from "react";
import CardDesign from "./CardDesign";
import Image from "../assets/Image";
import Navbar from "./Navbar";

export default function ProductList() {
  const products = [
    {
      id: 1,
      imgsrc: `${Image.sparx2}`,
      brandName: "Sparx",
      description: "SP-236 Casual..",
      currentPrice: "₹500",
      previousPrice: "₹1,000",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 2,

      imgsrc: `${Image.asian2}`,
      brandName: "Asian",
      description: "AS-620 Casual..",
      currentPrice: "₹800",
      previousPrice: "₹1,600",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 3,

      imgsrc: `${Image.campus}`,
      brandName: "Campus",
      description: "CA-454 Casual..",
      currentPrice: "₹1,500",
      previousPrice: "₹3,000",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 4,
      imgsrc: `${Image.sparx}`,
      brandName: "Sparx",
      description: "SP-236 Casual..",
      currentPrice: "₹500",
      previousPrice: "₹1,000",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 5,
      imgsrc: `${Image.asian}`,
      brandName: "Asian",
      description: "AS-620 Casual..",
      currentPrice: "₹800",
      previousPrice: "₹1,600",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 6,
      imgsrc: `${Image.aadi}`,
      brandName: "Aadi",
      description: "AD-620 Casual..",
      currentPrice: "₹900",
      previousPrice: "₹1,800",
      discount: "50% off",
      category: "Shoes",
    },
    {
      id: 7,
      imgsrc: `${Image.nokia}`,
      brandName: "Nokia",
      description: "Nokia 105 TA-..",
      currentPrice: "₹1,299",
      previousPrice: "₹1,599",
      discount: "18% off",
      category: "Phones",
    },
    {
      id: 8,
      imgsrc: `${Image.realme}`,
      brandName: "Realme",
      description: "realme C30(Denim..",
      currentPrice: "₹5,299",
      previousPrice: "₹8,499",
      discount: "29% off",
      category: "Phones",
    },
    {
      id: 9,
      imgsrc: `${Image.poccoX4}`,
      brandName: "Pocco",
      description: "POCO X4 Pro 5G..",
      currentPrice: "₹15,749",
      previousPrice: "₹22,999",
      discount: "31% off",
      category: "Phones",
    },
    {
      id: 10,
      imgsrc: `${Image.infinix}`,
      brandName: "Infinix",
      description: "Infinix Smart 6 HD..",
      currentPrice: "₹5,999",
      previousPrice: "₹8,999",
      discount: "33% off",
      category: "Phones",
    },
    {
      id: 11,
      imgsrc: `${Image.motorola}`,
      brandName: "Motorola",
      description: "Motorola G62 5G..",
      currentPrice: "₹15,499",
      previousPrice: "₹21,999",
      discount: "29% off",
      category: "Phones",
    },
    {
      id: 12,
      imgsrc: `${Image.polo}`,
      brandName: "Polo",
      description: "Men Striped Polo..",
      currentPrice: "₹279",
      previousPrice: "₹1,299",
      discount: "78% off",
      category: "Fashion",
    },
    {
      id: 13,
      imgsrc: `${Image.halfshirt}`,
      brandName: "Qugue",
      description: "Men Regular Fit..",
      currentPrice: "₹299",
      previousPrice: "₹999",
      discount: "70% off",
      category: "Fashion",
    },
    {
      id: 14,
      imgsrc: `${Image.addidas}`,
      brandName: "Addidas",
      description: "Men Printed Roun..",
      currentPrice: "₹3,519",
      previousPrice: "₹4,999",
      discount: "29% off",
      category: "Fashion",
    },
    {
      id: 15,
      imgsrc: `${Image.allensolly}`,
      brandName: "Allen Solly",
      description: "Men Slim Fit Che..",
      currentPrice: "₹2,499",
      previousPrice: "₹4,999",
      discount: "49% off",
      category: "Fashion",
    },
  ];
  return (
    <>
      <Navbar products={products} />
    </>
  );
}
